name: Deploy API to Heroku on merge to master branch

'on':
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tlm-api"
          heroku_email: "reklam11@gmail.com"
          appdir: api
          usedocker: true


